image:
  file: .gitpod.Dockerfile

checkoutLocation: modules/lib/golioth

tasks:
  - init: |
      west update
      printf '[manifest] \npath = modules/lib/golioth \nfile = west.yml' >> /workspace/.west/config
      sudo west completion bash > /etc/bash_completion.d/west-completion.bash
    command: |
      export ZEPHYR_BASE=/workspace/zephyr

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
