manifest:
  projects:
    - name: zephyr
      revision: 7d27f8dd583da5fbcda7167bc0b9ec9aa7d3dad1
      url: https://github.com/zephyrproject-rtos/zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - hal_espressif
          - hal_nordic
          - hal_st
          - hal_stm32
          - mbedtls
          - mcuboot
          - mcumgr
          - net-tools
          - segger
          - tinycrypt
          - zcbor

    - name: qcbor
      revision: 17b5607b8c49b835d22dec3effa97b25c89267b3
      url: https://github.com/golioth/QCBOR.git
      path: modules/lib/qcbor

  self:
    path: modules/lib/golioth
    west-commands: scripts/west-commands.yml
