manifest:
  projects:
    - name: zephyr
      revision: d490358e283fce891c4b867653a75ce55791a5a2
      url: https://github.com/zephyrproject-rtos/zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - hal_espressif
          - hal_nordic
          - hal_st
          - hal_stm32
          - mbedtls
          - mcuboot
          - mcumgr
          - net-tools
          - segger
          - tinycrypt
          - zcbor

    - name: qcbor
      revision: 17b5607b8c49b835d22dec3effa97b25c89267b3
      url: https://github.com/golioth/QCBOR.git
      path: modules/lib/qcbor

  self:
    path: modules/lib/golioth
    west-commands: scripts/west-commands.yml
